---

- name: get stats from interface(s) on nexus 9000
  hosts: n9k
  connection: local
  gather_facts: no

  vars:
    key_id: 'nxapi_intf_091714'

  pre_tasks:

  - name: tweet start of playbook
    tweet: msg='@jedelman8 - start of playbook execution' auth={{ creds }} key={{ key_id }}


  tasks:

  - name: get interface stats
    intf_stats: 
      ip={{ inventory_hostname }}
      interface=Ethernet1/4
    register: results

  - tweet: 
      msg="@jedelman8 {{ inventory_hostname }}-- {{ results.stats.name }} has {{results.stats.crc_errors }} crc errors"
      auth={{ creds }}
      key={{ key_id }}


  - name: prepare report based on template
    template: src=templates/interface_stats.j2 dest=reports/{{ inventory_hostname }}.stats


  post_tasks:

  - name: tweet end status of playbook
    tweet: msg='@jedelman8 - end of playbook' auth={{ creds }} key={{ key_id }}
